### ISSUE TITLE
double-click (preview file) issue

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-elfinder#10]
![elfinder-doubleclick-issue](https://user-images.githubusercontent.com/9800/127701453-62df030c-c502-49c8-a5a4-43ffacfebdf6.png)

return "404 page not found" where am i wrong ?

the link tries to load this url :
`http://localhost:8080/elfinder/proxy/index?baseUrl=QHdlYi9maWxlcw%3D%3D&path=hires_1847926.png&_t=1627710808`

**Comment by paskuale75** [comment]
@simialbi should i maybe add a proxyController in my module and extend it from elfinder ?

**Comment by simialbi** [comment]
Hmmm.... I'll fix it

**Comment by paskuale75** [comment]
I add a P.R.
