### ISSUE TITLE
custom label for folders

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-elfinder#14]
Hi @simialbi is there the possibility to show a different label in display, leaving the connectionSets structure intact? I am attaching an image where the name next to the root is taken from the connectionsSets array.

thanks
![Schermata da 2021-11-03 10-01-43](https://user-images.githubusercontent.com/9800/140033908-77d0d7ce-a9f1-44c9-820c-38734aa44127.png)

**Comment by simialbi** [comment]
I think `alias` is what you're looking for:
```php
'modules' => [
    'elfinder' => [
        'class'          => 'simialbi\yii2\elfinder\Module',
        'connectionSets' => [
            'default' => [ // like elfinder roots
                [
                    'alias' => 'My root folder name', // <== HERE
                    'class' => 'simialbi\yii2\elfinder\ElFinderConfigurationLocalFileSystem',
                    'path'  => '@webroot/files',
                    'URL'   => '@web/files'
                ]
            ]
        ]
    ]
]
```

**Comment by paskuale75** [comment]
Great, thanks @simialbi
