### ISSUE TITLE
upload size limit 

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-elfinder#17]
Hi @simialbi, I tried to load two folders with other subfolders and some top level files inside them, at the end without giving me any exception I find the two folders and subfolders empty and some of the top level files copied others not, in all these two folders have a size of 450MB.
is there any kind of limit in this plugin ?

thanks

**Comment by paskuale75** [comment]
It's not elfinder issue, sorry.

**Comment by simialbi** [comment]
Hi @paskuale75 
Yes I think it's an configuration thing with apache or nginx. I'm glad to hear you found it yourself 😄
