### ISSUE TITLE
google drive

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-elfinder#21]
any examples of use with google drive? 
thanks

**Comment by simialbi** [comment]
It's not yet implemented. Would you like to use it?

**Comment by paskuale75** [comment]
Yes, I would really like to make it happen if it's possible. If there are
instructions on how to get started I would try with some pull commits.

Il Lun 22 Lug 2024, 13:31 simialbi ***@***.***> ha scritto:

**Comment by simialbi** [comment]
I added [GoogleDriveConfiguration](https://github.com/simialbi/yii2-elfinder/blob/master/src/ElFinderConfigurationGoogleDrive.php) to the master branch, but don't have tested. Change the version of elfinder to `dev-master` in your `composer.json`, so you can test it. You have to at least fill:
```php
    'connectionSets' => [
        'default' => [ // like elfinder roots
            [
                'class' => 'simialbi\yii2\elfinder\ElFinderConfigurationGoogleDrive',
                'connection_id' => '',
                'client_secret' => ''
            ]
        ]
    ],
```
(according to elfinder issue comments)

**Comment by paskuale75** [comment]
Thanks, I'll check it out!

Il Lun 22 Lug 2024, 15:56 simialbi ***@***.***> ha scritto:

**Comment by paskuale75** [comment]
In my module init events I've a loop for create N connectionSets:

```
$connectionSets['pratica-' . $praticaId] = [
                    [
                        'alias' => $alias, // <== HERE
                        'class' => 'simialbi\\yii2\\elfinder\\ElFinderConfigurationGoogleDrive',
                        'client_id' => '***************-ka************ec4oukul54if6o2708c.apps.googleusercontent.com',
                        'client_secret' => '*******************'
                    ]
                ];
```

I clean the cache for change from filesystem to google drive but console get this to me:

![elfinder_gdrive_clientid_issue](https://github.com/user-attachments/assets/17b8dea4-52a2-4f20-9f67-3500ade90c2f)

thanks

**Comment by simialbi** [comment]
Hmmm... Ok. I'll have a look

**Comment by paskuale75** [comment]
Ok, thanks.

Il Mer 24 Lug 2024, 17:24 simialbi ***@***.***> ha scritto:

**Comment by paskuale75** [comment]
Hi @simialbi all fine there ? Any news for me ? Thanks

**Comment by simialbi** [comment]
Hi @paskuale75 

I try to fix it this week

**Comment by simialbi** [comment]
Yeah seems not to be this easy any more. You first have to get an access token and code it yourself:
https://developers.google.com/identity/protocols/oauth2/web-server?hl=it

My suggestion: Don't touch it
