### ISSUE TITLE
Unable to set URL under connectionSets

### ISSUE THREAD

**Issue by iamnareshsaini** [simialbi/yii2-elfinder#3]
```
 'connectionSets' => [
                'default' => [ // like elfinder roots
                    [
                        'class' => 'simialbi\yii2\elfinder\ElFinderConfigurationLocalFileSystem',
                        'path'  => '@webroot/uploads',
                        'URL'   => '@web/file/files'
                    ]
                ]
            ],
```

This is how I have defined URL `  'URL'   => '@web/file/files'` where `file` is my controller and `files` is my action . 
Could you please let me know how exactly this URL show be passed in yii2 basic template .

`127.0.0.1:8080/project/elfinder/proxy/index?baseUrl=QHdlYi9maWxlL2ZpbGVz&path=/NewFolder/file_example_PNG_500kB.png&_t=1587811929`

**Comment by simialbi** [comment]
The Module automatically rewrites your URL by one used via [ProxyController](https://github.com/simialbi/yii2-elfinder/blob/master/controllers/ProxyController.php) here:
https://github.com/simialbi/yii2-elfinder/blob/master/Module.php#L129
This guarantees always working URLs on all systems with no encoding problems or strange filenames behaviors. If I understand correctly: what you'd like to do is use without this proxy controller?

**Comment by iamnareshsaini** [comment]
Thanks for the response .Url manager helped me in this scenario . Really appreciate your work .

**Comment by simialbi** [comment]
I'm glad to hear you could solve it yourself. Thx 4 the post of your solution
