### ISSUE TITLE
Data is not in JSON format.

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-elfinder#6]
Invalid response from the backend. The data is not in JSON format. 

Thanks

**Comment by simialbi** [comment]
Do you have an example? Which URL does not return JSON? What is returned instead?

**Comment by paskuale75** [comment]
URL ->  `http://localhost:8080/elfinder/connection?instanceName=pratica-1&cmd=open&target=&init=1&tree=1&_=1627567646415`

**Comment by simialbi** [comment]
The URL seems to be wrong. With the solution I coded, elfinder is a submodule of `pratica`, so the URL should look like this:
ttp://localhost:8080`/pratica`/elfinder/connection?instanceName=pratica-1&cmd=open&target=&init=1&tree=1&_=1627567646415

**Comment by paskuale75** [comment]
Also happens if I use 'default' connectionSet as in documentation, here the url:
`http://localhost:8080/elfinder/connection?instanceName=default&cmd=open&target=&init=1&tree=1&_=1627570414917`

**Comment by paskuale75** [comment]
sorry my mistake, I had added a VarDumper :: dump in the @vendor code, I close the issue.
